### ISSUE TITLE
能否在config.ini文件里加个记住快捷键的参数

### ISSUE THREAD

**Issue by 1789984734** [SeaYJ/MouseClick#3]
每次打开都需要重新设置快捷键觉得有点繁琐

**Comment by SeaYJ** [comment]
> 每次打开都需要重新设置快捷键觉得有点繁琐

下个版本正在实现该功能，嘿嘿嘿~因为在学习，还望稍等一段时间哇😋~

**Comment by 1789984734** [comment]
期待

**Comment by SeaYJ** [comment]
> 期待

#2255a87651c94846941bda7e7b629b1d3ed3fe46

已更新，久等了~
感谢建议😘

**Comment by 1789984734** [comment]
马上体验

**Comment by SeaYJ** [comment]
> 马上体验

好的，有什么问题还希望及时反馈，非常感谢您的支持😋~
能被认可，真的很开心🌹~
